# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-12-05 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20181205_0137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productwwww',
            new_name='Produ',
        ),
    ]
