# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-12-05 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20181205_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='produ',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
