# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-12-05 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_produ_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produ',
            name='sku',
            field=models.CharField(max_length=20),
        ),
    ]
