# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-12-05 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20181205_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produ',
            name='qty',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
